### ISSUE TITLE
Incorrect dependencies for restrend

### ISSUE THREAD

**Issue by iembry-USGS** [USGS-R/restrend#2]
Hi, restrend is still dependent on USGSwsStats  and USGSwsQW.

This is the error message that I received when I attempted to install restrend:

ERROR: dependencies ‘USGSwsStats’, ‘USGSwsQW’ are not available for package ‘restrend’

Thank you.

**Comment by dlorenz-usgs** [comment]
Did you try to install the core USGS packages first? I just checked, they
are all available in gitHub. easiest way:

install.packages("restrend", repos=c("http://usgs-r.github.com","
http://cran.us.r-project.org"), dependencies=TRUE)

Dave

**Comment by iembry-USGS** [comment]
I didn't install the core USGS packages first. Thank you Dave. That code fixed the issue.
