### ISSUE TITLE
Possible bug in censSeaken or median.mcens

### ISSUE THREAD

**Issue by tjmills** [USGS-R/restrend#5]
When calculating the median of two identical vectors median.mcens() gives a different result than median(). This causes slopes to be possibly be calculated incorrectly in censSeaken when there are no censored data. I have suggested a change in a pull request.

A reproducible example is below

``` r

losl <- c(-430,
          -105,
          13.33333333,
          -57.5,
          133.2,
          4.166666667,
          -82.71428571,
          33.75,
          2.888888889,
          220,
          235,
          66.66666667,
          274,
          91,
          -24.83333333,
          100,
          57,
          250,
          -10,
          292,
          58.75,
          -73.8,
          80,
          33.71428571,
          -270,
          313,
          -5,
          -154.75,
          46,
          -2.333333333,
          896,
          127.5,
          -116.3333333,
          125,
          51.2,
          -641,
          -622.5,
          -132,
          -160,
          -604,
          122.5,
          0.333333333,
          849,
          302.5,
          -244,
          -80,
          -55,
          16.66666667,
          -171.25,
          -142.3,
          27,
          -136.1428571,
          -74.75,
          -43.66666667,
          -30,
          65,
          -201.6666667,
          -157.875,
          48.4,
          -145.5,
          -74,
          -39.125,
          160,
          -287.5,
          -200.5,
          68,
          -168.6,
          -81.33333333,
          -40.42857143,
          -735,
          -380.75,
          37.33333333,
          -250.75,
          -129.6,
          -73.83333333,
          -26.5,
          423.5,
          -89.33333333,
          21.75,
          58.4,
          873.5,
          -120.75,
          37.83333333,
          79.625,
          -1115,
          -380,
          -185,
          355,
          280,
          205,
          -270,
          -120,
          2.5,
          -59.4,
          42.33333333,
          -107,
          -48.25,
          -41.11111111,
          -45,
          93.33333333,
          -6.75,
          104.8,
          -79.83333333,
          -16.57142857,
          -12.5,
          370,
          31.5,
          204.6666667,
          -97.25,
          -5.2,
          -1.666666667,
          -307,
          122,
          -253,
          -99,
          -76,
          551,
          -226,
          -29.66666667,
          -18.25,
          -1003,
          -320,
          -208,
          363,
          189.5,
          16,
          -50,
          -145,
          -110,
          -51.8,
          -13.83333333,
          -38.57142857,
          -9,
          -59.22222222,
          -240,
          -140,
          -52.25,
          -6.6,
          -36.66666667,
          -3.142857143,
          -60.375,
          -40,
          10.33333333,
          51.75,
          4,
          36.33333333,
          -34.71428571,
          35.5,
          82.33333333,
          15,
          51.6,
          -33.83333333,
          176,
          -5.5,
          62.33333333,
          -68.5,
          -187,
          5.5,
          -150,
          198,
          -131.5,
          -461)


hisl <- losl

median(smwrQW::as.mcens(losl, hisl))
median(losl)
```

**Comment by tjmills** [comment]
https://github.com/USGS-R/restrend/blob/4fa149c4dbe6b127361080f29a8d1a963af8258e/R/censSeaken.R#L157-L160

**Comment by dlorenz-usgs** [comment]
Joe,
  The median is computed in a different way for data of type mcens. It
selects the larger of the two middle values in the case of an even-numbered
length of data. That is the method used by the survival folks, which is
used for mcens data. A note should be added to the documentation.
Dave

**Comment by tjmills** [comment]
OK, but why is a dataset with no censored values treated as censored data? Is there a seaken function in restrend that I am missing? The only one I could find was censSeaken.

**Comment by dlorenz-usgs** [comment]
Joe,
  It does not matter that the data are not censored--it matters only that
the type is mcens,
  Look at the seaken function in smwrStats for data that are not censored.
Dave

**Comment by tjmills** [comment]
Thanks I will take a look at that, but one more question.

If I were to feed in a dataset to one of the high-level restrend functions, and some of the sites contained no censored data, would restrend do the appropriate thing and calculate the slope based off of median() instead of median(as.mcens()) ?

**Comment by dlorenz-usgs** [comment]
Joe,
  If the data are uncensored, or less than the user-specified censoring
threshold, then seaken is used and not censSeaken.
Dave

**Comment by tjmills** [comment]
OK great, thanks Dave! I just wanted to make sure. I suggest adding either a check to censSeaken similar to what I have done, or a warning message informing the user that no censored data were found and that they should use smwrStats::seaken instead.

It is not apparent to the user that the slope is calculated using a different method than median when there are no censored data.
